# Generated by Django 4.0.4 on 2022-04-13 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentname', models.CharField(max_length=100)),
                ('studentaddress', models.CharField(max_length=200)),
                ('studentnumber', models.IntegerField()),
                ('studentemail', models.EmailField(max_length=100)),
            ],
        ),
    ]
