# Generated by Django 4.0.4 on 2022-04-19 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentapp', '0003_alter_student_studentid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='studentid',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
